%sh{kak-lsp --kakoune -s $kak_session}
lsp-start
lsp-auto-hover-enable
set-face global DiagnosticError white,red
set-face global DiagnosticWarning black,yellow

add-highlighter global number_lines -relative -hlcursor
add-highlighter global show_matching
set-face global MatchingChar white,blue

define-command fuzzy-find -params 1 -shell-candidates %{ rg --files } -docstring 'Fuzzy find a file with Ripgrep.' -hidden %{ edit %arg{1} }
map global user p :fuzzy-find<space> -docstring 'fuzzy finder'

set-option global grepcmd 'rg --column --no-heading --line-number --smart-case --hidden'

map -docstring 'case insensitive search' global user '/' /(?i)
map -docstring 'case insensitive backward search' global user '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global user '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global user '<a-?>' <a-?>(?i)
